apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: quarkus-gke
  name: quarkus-gke
spec:
  replicas: 2
  selector:
    matchLabels:
      run: quarkus-gke
  template:
    metadata:
      labels:
        run: quarkus-gke
    spec:
      containers:
      - image: gcr.io/capgemini-gcp/quarkus-gke:latest
        name: quarkus-gke
        readinessProbe:
          httpGet:
            port: 8080
            path: /health
          initialDelaySeconds: 1
        livenessProbe:
          httpGet:
            port: 8080
            path: /health
          initialDelaySeconds: 1        
        ports:
        - containerPort: 8080