apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: quarkus-ms-demo
  name: quarkus-ms-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      run: quarkus-gke
  template:
    metadata:
      labels:
        run: quarkus-gke
    spec:
      containers:
      - image: gcr.io/alpine-comfort-268715/qquarkus-gke:latest
        name: quarkus-gke
        ports:
        - containerPort: 8080